services:
    jupyter:
        build:
            context: .
            dockerfile: Dockerfile
        image: elifesciences/sciencebeam-usage-examples:${IMAGE_TAG}
        user: root
        command: start-notebook.sh --NotebookApp.token=''
        environment:
          - CHOWN_HOME=yes
          - "CHOWN_HOME_OPTS=-R"
          - NB_UID=${USER_ID:-1000}
          - NB_GID=${GROUP_ID:-1000}
        ports:
            - "${SCIENCEBEAM_USAGE_EXAMPLES_JUPYTER_PORT}:8888"
        volumes:
            - ./.temp:/home/jovyan/.temp
            - ./notebooks:/home/jovyan/notebooks
